version: '3.6'

services:
  nginx:
    build:
      context: srcs/requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception
    volumes:
      - .:/var/www/
    #   - ./srcs/requirements/tools:/etc/nginx/http.d/
    #   - ./srcs/requirements/tools:/etc/nginx/ssl/
  mariadb:
    build:
      context: srcs/requirements/masha/
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - .:/var/lib/mysql
    networks:
      - inception
    environment: 
      - srcs/requirements/masha/.env
  wordpress:
    container_name: wordpress
    build: srcs/requirements/wordpress
    image: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - .:/var/www/html
networks:
  inception:
    name: inception
    driver: bridge