version: '3.6'

services:
  nginx:
    build:
      context: srcs/requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception
    volumes:
      - www:/var/www/
  mariadb:
    build:
      context: srcs/requirements/masha/
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    environment: 
      - srcs/requirements/masha/.env
  wordpress:
    container_name: wordpress
    build: srcs/requirements/wordpress
    image: wordpress
    env_file: .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - www:/var/www/html
volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_WWW_PATH}
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DB_PATH}
      o: bind

  #============================================================================#
networks:
  inception:
    name: inception
    driver: bridge
