
version: '3'

services:

  nginx:
    build:
      context: srcs/requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - www:/var/www/

  mariadb:
    build:
      context: srcs/requirements/masha/
      dockerfile: Dockerfile
      args:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    env_file: .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: srcs/requirements/wordpress/
      dockerfile: Dockerfile
      args:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    image: wordpress
    depends_on:
      - mariadb
    env_file: .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - www:/var/www

volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_WWW_PATH}
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DB_PATH}
      o: bind

  #============================================================================#
networks:
    inception:
        driver: bridge