version: '3'

services:
  nginx:
    build:
      context: srcs/requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    # volumes:
    #   - ./srcs/requirements/tools:/etc/nginx/http.d/
    #   - ./srcs/requirements/tools:/etc/nginx/ssl/